### PR TITLE
Removed dead code which triggers TypeError

### PR DESCRIPTION
**Pull request by deguif**
image

### CODE REVIEW

**Comment by deguif** [comment]
ping @lisposter 
Can you have a look at this ?

**Comment by lisposter** [comment]
@deguif sorry, too much work to do these days. Can you please pointed out that, how this error occur, I can't reproduce it.

**Comment by deguif** [comment]
When destroying the ZeroClipboard object. 
In my case it's when using the ZeroClipboard in a boostrap modal (angular-ui) and when closing the modal, this error occurrs.

**Comment by lisposter** [comment]
if you just delete that line, line 53 and line 75 will be useless, consider it

**Comment by deguif** [comment]
I'm writing a JS fiddle so that the error can be reproduced.

**Comment by deguif** [comment]
Finally, by updating to ZeroClipboard 2.2.0, the problem diseapeared.
So this was more a problem on ZeroClipboard code.

Sorry for the noise. This PR can be closed.

**Comment by lisposter** [comment]
ok, any way, thank you! :beers:

**Pull request closed without merging**
